- name: Install nginx
  package:
    name: [nginx, python3-libselinux, python3-policycoreutils]
    state: present

- name: Enable and restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes

- name: Allow nginx to listen port 443
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  with_items: 
    - 80

- name: Configure firewalld
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: 
    - 80

- name: Allow nginx to proxy pass
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: not disable_selinux

- name: copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/sciqlop.conf
    owner: root
    group: root
    mode: '0644'

- name: Allow nginx to read /srv
  community.general.sefcontext:
    target: '/srv(/.*)?'
    setype: httpd_sys_content_t
    state: present
  when: not disable_selinux

- name: Allow nginx workers to open as much files as possible
  community.general.pam_limits:
    domain: nginx
    limit_type: hard
    limit_item: nofile
    value: unlimited

- name: Enable service nginx
  service:
    name: nginx
    enabled: yes
    state: restarted